### ISSUE TITLE
This is currently broken, any plans to fix it? I'd like to use the API

### ISSUE THREAD

**Issue by xplshn** [Kkordik/DiagramAPI#1]
I wanted to use the API [here](https://hf.co/chat/assistant/6671f1e4f3898f7f798d3f53), but it is currently broken, and I haven't found any alternatives either, I tried to make the GPT made by Whimsical give me its system prompt, and it did, but obfuscated the URL...

https://hf.co/chat/assistant/6671f1e4f3898f7f798d3f53

**Comment by xplshn** [comment]
Fixed the issue: Replaced with another service

**Comment by Kkordik** [comment]
Hello, thanks for your interest. 
You could follow the steps from readme and host it on your own.
